### ISSUE TITLE
Point of Sale app never progresses past the QR screen

### ISSUE THREAD

**Issue by scottwilson312** [solana-labs/solana-pay#109]
I followed the instructions in the README

```
1) git clone https://github.com/solana-labs/solana-pay.git
2) cd solana-pay/point-of-sale
3) yarn install
4) yarn start
5) http://localhost:1234?recipient=caPsEFqXeu4upjqorwqhhTjmnhtob9EBUsAx7HbXpqw&label=Your+Store+Name
6) Scan QR code with Phantom iOS wallet
7) Send SOL
```

The SOL gets sent, I can see the transaction just fine on my phantom wallet, however, the Point of Sale app never leaves the QR code page. I am assuming it is supposed to show a spinner or a confirmation page at this point.

Thank for you for any help and apologies if I misunderstood what that PoS app is supposed to do !

**Comment by scottwilson312** [comment]
Closing this issue as I think this is more of a discord appropriate question.

**Comment by scottwilson312** [comment]
Okay after wathcing some youtube videos, I think this is a real issue.

**Comment by jordansexton** [comment]
When running from the cloned repo on localhost, you're using devnet which means your Phantom wallet must also be configured to use devnet. Is it?

**Comment by scottwilson312** [comment]
Nope, that was my problem. And it's right there in the README. I just skimmed over that as I already have a wallet 🤦🤦🤦🤦🤦🤦.

Apologies for posting this without giving the README a more thorough read through. 

Thanks for the response, much appreciated. This is great.

**Comment by jordansexton** [comment]
No problem, glad it's working!
