### ISSUE TITLE
Simple readme needed

### ISSUE THREAD

**Issue by anhbaysgalan1** [solana-labs/solana-pay#11]
Hello dear solana-pay team! 

I wanted to contribute this project. Don't have any documentation for initial setup. 

Please write simplest documentation for development. 

Thanks @garious @oJshua @sakridge @aeyakovenko @jordansexton

**Comment by jordansexton** [comment]
Hey, there's no need to tag a ton of devs on issues like this. Right now the only documentation is the code, and as noted in the top level readme, this isn't ready for use yet.

I'm available on the Solana Discord if you have specific questions or want to find out how to contribute.

**Comment by jordansexton** [comment]
@anhbaysgalan1 there's now a bunch of documentation. Please check it out :)
