### ISSUE TITLE
Privacy Concerns with using Solana Pay

### ISSUE THREAD

**Issue by edyuan** [solana-labs/solana-pay#116]
I was wondering if there are privacy issues with using Solana Pay since both the merchant and customer are now aware of each other's wallet addresses?  I think this means each could peruse through the other's transaction history.  Please let me know if this is already addressed somehow.

**Comment by jordansexton** [comment]
This isn't a concern that's specific to Solana Pay. Any transaction on a public ledger can be traced this way. I'm excited for privacy solutions on Solana, but they are out of scope for this repo. Please ask in Discord!
