### ISSUE TITLE
Can Solana point-of-sale work as a webhook?

### ISSUE THREAD

**Issue by redniche** [solana-labs/solana-pay#118]
I was really impressed with this project. 

I have a question, and if you look at the contents of "4.1 Retries" in the current solana docs, pos uses the polling strategy to check whether a transaction has been confirmed.
Is there no way to implement this as a webhook? 

If there is a way, please let me know how it can be done.
I think it would be more appropriate to use a webhook rather than polling.

**Comment by jordansexton** [comment]
We don't use Github for general questions. Please ask on the Solana Discord, there's a #solana-pay channel.
