### ISSUE TITLE
[feature] Plugin for Saleor Headless Ecommerce

### ISSUE THREAD

**Issue by ndjido** [solana-labs/solana-pay#121]
Hi team,

I am working on a Solana based NFTs project. We happen to use `Saleor headless e-commerce` platform for our shop. 
I think it would be great to integrate `Saleor` as one of the e-commerce platform to integrate `Solana Pay` with. 

Let me know what you think.

Cheers

**Comment by jordansexton** [comment]
We aren't considering adding integrations with any e-commerce platforms as part of the core for Solana Pay. However, we welcome any community efforts to support these platforms, and we could add links to them if this is something you end up building. Please join us in the #solana-pay channel on the Solana Discord: https://discord.com/invite/solana
