### ISSUE TITLE
I got CORS issue on https://solanapay.genesysgo.net/ 

### ISSUE THREAD

**Issue by yao3060** [solana-labs/solana-pay#124]
![image](https://user-images.githubusercontent.com/1792115/165879234-3fbb45f7-b2be-41eb-8b4e-fbf82c03875f.png)

Since yesterday afternoon (2022-04-28 utc+8)

Does anybody know?

**Comment by jordansexton** [comment]
This is a new issue with GenesysGo -- they have started requiring authorization to use the API.

For now, I'd try using `https://api.mainnet-beta.solana.com`. @cogoo we should get to the bottom of this and update the point of sale app if needed.

**Comment by jordansexton** [comment]
Reopened this issue until we update the app / docs.

**Comment by metasal1** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/54984459/167591596-73433278-7d62-469f-a6eb-4fa2126c32f1.png">
Mainnet getting 429.

There seems to be a infinite loop when on the number pad screen and on the qr code.

There shouldn't be any reason to call the API at these stages.

**Comment by metasal1** [comment]
Ok - based on further reading, it seems yes we do need to poll the API for status changes.

In the interim, I have set the API endpoint to https://solana-mainnet.phantom.tech/ so Phantom wallets are go for now.

**Comment by jordansexton** [comment]
Thanks @metasal1, I updated the default (16c6f56f4bcc77ec7518b8081f72102e756661a6) to use Phantom's endpoint per your testing.
