### ISSUE TITLE
Generated QR code not working

### ISSUE THREAD

**Issue by victorbianconi** [solana-labs/solana-pay#126]
After having followed all the steps for the merchant account and the generation of a QR code which the customer has to scan, the QR code simply does not work. 

This is an example of QR code generated through the `createQR `method imported from `@solana/pay`

![Immagine 2022-05-06 151217](https://user-images.githubusercontent.com/64693573/167138242-5f9c2efd-de9a-4474-86b2-baec9d21905f.png)

Am I doing something wrong or is it a global issue?

**Comment by hendrikhendrik** [comment]
same i also have same problem

**Comment by jordansexton** [comment]
Hmm, something looks wrong with the QR code -- it's missing some of the corners. Can you link me to a project where this is happening? We've tested this in the reference implementation [point of sale app](https://github.com/solana-labs/solana-pay/tree/master/point-of-sale) quite a bit.

**Comment by hendrikhendrik** [comment]
may be out put qrcode https:// where i can find output QR Code 
![err](https://user-images.githubusercontent.com/40292542/167586531-547eb995-0bd1-45c0-8f55-ef59f0714bf0.jpg)
?

**Comment by tarcisiozf** [comment]
@hendrikhendrik try using the ssl proxy by running `yarn proxy`
