### ISSUE TITLE
wallet integration link is not working

### ISSUE THREAD

**Issue by NR-NJN** [solana-labs/solana-pay#127]
https://docs.solanapay.com/core/wallet-integration

**Comment by metasal1** [comment]
New link https://docs.solanapay.com/core/transfer-request/wallet-integration

**Comment by jordansexton** [comment]
@NR-NJN could you mention where the dead link is?

**Comment by metasal1** [comment]
https://github.com/solana-labs/solana-pay/blob/51e7d02091e9b37ae1a6de68791b11be1488e432/core/README.md
