### ISSUE TITLE
complete

### ISSUE THREAD

**Issue by hendrikhendrik** [solana-labs/solana-pay#128]
i have problem with complete transasic issued local host change from  http://localhost:3000/ to http://localhost:3001/new?recipient= , how i can changed it back to  http://localhost:3000/ after  complete transasic
![err1](https://user-images.githubusercontent.com/40292542/167608865-28b5f7eb-a1ad-411a-911a-6d0d10733db1.jpg)

**Comment by jordansexton** [comment]
You need to run `yarn proxy` when running this locally: https://github.com/solana-labs/solana-pay/tree/master/point-of-sale#in-a-separate-terminal-run-a-local-ssl-proxy

This will run an HTTPS server on port 3001. Then you need to open `https://localhost:3001?...` (note the `https`).

**Comment by hendrikhendrik** [comment]
i alreday run yarn dev in first terminal and yarn proxy  in second terminal. still same problem after scan barcode and complete tansaction and clik start over return in same error
