### ISSUE TITLE
createQR(url) function error

### ISSUE THREAD

**Issue by a-creation** [solana-labs/solana-pay#146]
After following documentation specification for using the createQR(url), createQR errors: ReferenceError: Can't find variable: document.

` const url = encodeURL({ recipient, amount, splToken, reference, label, message, memo });
    const qrCode = createQR(url);`

![IMG_3E2F189ED4B7-1](https://user-images.githubusercontent.com/60591313/185777557-0fc2949a-4823-43ff-8756-2a34cf557c12.jpeg)

**Comment by jordansexton** [comment]
This isn't a bug with the library. You're using it inside React Native, and that QR code library depends on the DOM.

**Comment by a-creation** [comment]
@jordansexton What is the best practice to generate this QR code within React Native?

**Comment by jordansexton** [comment]
I couldn't tell you specifically :)

But it's just a URL string that's being encoded, so any QR code library that works natively or without requiring the DOM should be good.

**Comment by samheutmaker** [comment]
@a-creation A little late, but [here](https://www.npmjs.com/package/react-native-qrcode-svg) is a good QR Code library for react-native.

Example:

```.ts
import React from 'react';
import QRCode from 'react-native-qrcode-svg';
import { encodeURL } from '@solana/pay';

const MyComponent: React.FC = () => {
  const url = 'https://...'; // Your url here
  const encoded = encodeURL({ link: new URL(url) });

  return (
    <QRCode
      value={encoded.toString()}
      size={300}
    />
  );
};
```
