### ISSUE TITLE
Solana pay transaction request fails on devnet during transaction simulation

### ISSUE THREAD

**Issue by peerwaya** [solana-labs/solana-pay#153]
Solana pay transaction request fails on `devnet` during transaction simulation, switching to `mainnet` works. Not sure why this thought, I expected that the transaction simulation should use `devnet` cluster instead of `mainnet` since the cluster on the wallet was explicitly set to `devnet`.

Though phantom says unable to simulate transaction,  the approve button is disabled.

![image](https://user-images.githubusercontent.com/14053870/187802133-b9b5f11e-735c-416e-ac2e-980579ffea17.png)

**Comment by jordansexton** [comment]
This isn't an issue with Solana Pay. Please report issues with Phantom to them!
