### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by sanaderi** [solana-labs/solana-pay#188]
How can I debug the solana pay process?

this website don't work:
https://glow.app/test/solana-pay

 and when I use phantum wallet, it's crashed.

**Comment by mcintyre94** [comment]
Hey! Issues on this repo aren't really a good place to help with this sort of thing, the stackoverflow is best: https://solana.stackexchange.com/  We'd need more information to help there though, and preferably source code.

We don't maintain the glow.app page you linked, you'd need to contain Glow Wallet about that

In general wallet browser extensions will have better/more accessible logging than mobile ones. So a common method I use to debug Solana Pay transaction requests (if that's what you're using) is to connect a browser wallet and send the transaction being returned to that. You'll usually get some logging in the browser console if there are any issues there.

To save you writing the code for that yourself you might want to use the pay scaffold here: https://github.com/solana-labs/solana-pay-scaffold If you just change the API route code there to return your transaction, you should be able to send it to a browser wallet and get some handy debug logging.

If you still have an issue after doing that, please open a question on the stackexchange including as much detail as you can, particularly the logged messages and the API code will be useful. Feel free to post the link to that question on here and I'll take a look :)

**Comment by sanaderi** [comment]
Thanks for your reply. I need implement it's with Laravel  or nuxtjs?
Is there a ready plugin or documentation?

https://solana.stackexchange.com/questions/5567/solana-pay-with-laravel
