### ISSUE TITLE
Confirmed Page Not Showing Up

### ISSUE THREAD

**Issue by DimensionCoin** [solana-labs/solana-pay#198]
After i scan the scan the qrcode with my mobile wallet and approve the transaction nothing happens on my desktop, the ConfirmedPage is not showing up.

**Comment by mcintyre94** [comment]
@DimensionCoin are you using Phantom by any chance? There's a bug in their current mobile app where this is broken. If you're using Phantom please use a different wallet for now and check if that fixes it for you.
