### ISSUE TITLE
Transferring multiple NFTs in a single QR Code

### ISSUE THREAD

**Issue by notdanilo** [solana-labs/solana-pay#209]
Is there any way to send multiples NFTs in a single QR Code?

**Comment by mcintyre94** [comment]
Hey @notdanilo! Solana Pay transaction requests can work for any Solana transaction, so as long as you can do it in a single transaction it'll work.

If you're struggling to write such a transaction then please ask your question on solana.stackexchange.com - that's the best way to get help with things like this. You won't need to narrow your question to Solana Pay there, so should be able to get help from a much wider group of people. Thanks! :)
