### ISSUE TITLE
Error parsing recipient from url

### ISSUE THREAD

**Issue by mordonez-me** [solana-labs/solana-pay#215]
Encoding has the following format:

`solana:CaGyA2tPA3fgTf7vsqMb3PK7PZLSbeWb9HvfcgwzENaa/?amount=111000000&spl-token=2VhjJ9WxaGC3EZFwJG9BDUs9KxKCAjQY4vgd1qxgYWVg&label=nedpos&memo=a999e32a-9976-44ff-a85a-021369dbd8e8`

Then decoding uses pathname which returns `CaGyA2tPA3fgTf7vsqMb3PK7PZLSbeWb9HvfcgwzENaa/` and then try to use that in a PublicKey, which throws an error.

![image](https://github.com/solana-labs/solana-pay/assets/2242042/c20d5c76-3a86-4a82-8039-11c6598d1d98)

**Comment by jordaaash** [comment]
You have a `/` character after the recipient. This isn't valid.
