### ISSUE TITLE
Sol Pay method has little visibility/contrast on Shopify. 

### ISSUE THREAD

**Issue by chongkan** [solana-labs/solana-pay#221]
<img width="777" alt="image" src="https://github.com/solana-labs/solana-pay/assets/4944252/2e08368b-f15c-49ad-909c-86d04dab2c6d">

Perhaps we can add a setting to choose dark/light depending on the store theme. I think maybe the Solana Pay text should be an image similar to the Shop Pay one.

**Comment by Majidrazaee** [comment]
بله همینطور است

**Comment by jordaaash** [comment]
Thanks, this isn't the right repo for this issue though.

Please open this against https://github.com/solana-labs/solana-payments-app
