### ISSUE TITLE
Proposal: Solana Pay e-store directory

### ISSUE THREAD

**Issue by streamich** [solana-labs/solana-pay#223]
This is a feature request to create a directory of all online stores that support Solana Pay. Similar to to the [Solana Ecosystem page](https://solana.com/ecosystem) create a page where all e-commerce stores, which accept Solana Pay are listed.

**Comment by jordaaash** [comment]
This is just the repo for the Solana Pay code. We don't do promotion of projects here. The Solana Ecosystem site has a payments category, which would be a better place for this, or a new category.
