### ISSUE TITLE
I want to cancel my transaction and send to another wallet 41edaa5901d112216083edc935b268f0faffa0020ce6661e082e5f2b81e01a04

### ISSUE THREAD

**Issue by Isis831** [solana-labs/solana-pay#227]
I want to cancel my transaction and send to another wallet 41edaa5901d112216083edc935b268f0faffa0020ce6661e082e5f2b81e01a04

_Originally posted by @Jaemax1 in https://github.com/Blockchair/Deleted-Issues/issues/797_

**Comment by Jaemax1** [comment]
This issue was never solved but it's getting closed. Why?
