### ISSUE TITLE
I want to cancel my transaction and send to another wallet 41edaa5901d112216083edc935b268f0faffa0020ce6661e082e5f2b81e01a04

### ISSUE THREAD

**Issue by Isis831** [solana-labs/solana-pay#228]
I want to cancel my transaction and send to another wallet 41edaa5901d112216083edc935b268f0faffa0020ce6661e082e5f2b81e01a04

_Originally posted by @Jaemax1 in https://github.com/Blockchair/Deleted-Issues/issues/797_

_Originally posted by @Isis831 in https://github.com/solana-labs/solana-pay/issues/227_

**Comment by Majidrazaee** [comment]
بله من هم می‌خواهم لغو کنم
