### ISSUE TITLE
[improvement] Can't read the QR Code generated by `point-of-sale`

### ISSUE THREAD

**Issue by marc2332** [solana-labs/solana-pay#45]
Hello

I am unable to read any QR Code generated by the `point-of-sale` website. I think this is my phone's issue tho. For some reason, I can't read the QR code if it has a dark background.

![image](https://user-images.githubusercontent.com/38158676/152184214-cf5cf6a3-482a-4a60-a051-67a4e258a593.png)

Left = Original
Right = Tweaked by me

The left doesn't work, but, by tweaking the colors a bit (right) my phone is able to read it.

Maybe adding some kind of Dark/Light theme switcher would be helpful for those who can't read with the dark theme :))

btw, solana pay is awesome 💪🏻

**Comment by jordansexton** [comment]
Thanks for the report. The PoS app uses the light/dark mode from the system: https://github.com/solana-labs/solana-pay/blob/ebe5ad9dce68dfcafd426be02ebe2e34f90cd056/point-of-sale/src/components/contexts/ThemeProvider.tsx#L10-L25

However, I think to your point, we should probably try to increase the contrast and see if that helps. Can you tell me what phone / wallet you're scanning with and what kind of screen you're scanning?

**Comment by marc2332** [comment]
Phone: Xiaomi Redmi Note 6 Pro
Wallet: [Mine](https://github.com/marc2332/solana-mobile-wallet) and also MIUI's built-in QR Scanner (is not a wallet, but it should be able to read it anyway and output the payment uri, but it doesn't)
Screen: A monitor - Lenovo D27 30

😄

**Comment by jordansexton** [comment]
Hey, I just checked out https://github.com/marc2332/reactor-wallet -- this is awesome!

Could I ask you to try this branch? https://github.com/solana-labs/solana-pay/tree/point-of-sale/high-contrast/point-of-sale

3c81c3722da0d3acf72acc0cdf08e52f9828c879 just changes the gray/off-white colors to black/white for higher contrast.

**Comment by marc2332** [comment]
> Hey, I just checked out https://github.com/marc2332/reactor-wallet -- this is awesome!

Thank you very much! 😄  I really appreciate it

> Could I ask you to try this branch? https://github.com/solana-labs/solana-pay/tree/point-of-sale/high-contrast/point-of-sale
> 
> [3c81c37](https://github.com/solana-labs/solana-pay/commit/3c81c3722da0d3acf72acc0cdf08e52f9828c879) just changes the gray/off-white colors to black/white for higher contrast.

I am still unable to read it 😢

**Comment by jordansexton** [comment]
Okay, thanks for testing. It sounds like we need to always use a light background and dark foreground for the QR itself regardless of the page background.

**Comment by jordansexton** [comment]
This should be fixed now. Please test again?

**Comment by jordansexton** [comment]
<img width="460" alt="Screen Shot 2022-02-04 at 8 12 56 PM" src="https://user-images.githubusercontent.com/1173161/152624983-42cae188-81b7-4349-8cd7-47ba678f77d6.png">

**Comment by marc2332** [comment]
> <img alt="Screen Shot 2022-02-04 at 8 12 56 PM" width="460" src="https://user-images.githubusercontent.com/1173161/152624983-42cae188-81b7-4349-8cd7-47ba678f77d6.png">

This one works perfectly :) Thank you Jordan
