### ISSUE TITLE
Failed to find wallet-adapter-react-ui/styles.css'

### ISSUE THREAD

**Issue by ignatievvictor** [solana-labs/solana-pay#52]
Guys pls help with poin of sale app

parcel/transformer-postcss: Failed to find '../node_modules/@solana/wallet-adapter-react-ui/styles.css' in [ /user/solana-pay/point-of-sale/src ]
Error: Failed to find '../node_modules/@solana/wallet-adapter-react-ui/styles.css'
  in [
    /user/solana-pay/point-of-sale/src

**Comment by jordansexton** [comment]
Hmm, issues like this are typically due to not having installed the dependencies.

Can you try again, and make sure to follow these steps precisely? https://github.com/solana-labs/solana-pay/tree/master/point-of-sale#getting-started

**Comment by jordansexton** [comment]
Closing since I think this is an installation issue, but please comment if you're still seeing it.

**Comment by ignatievvictor** [comment]
Yes you was right. I miss this manual. Now all good. Thank you.
But tell me pls where i can join to some dev community to be in touch with you guys online.
Right now i try to connect a merchant to our platform and i need some advices and help.

**Comment by jordansexton** [comment]
Check out the #solana-pay channel in the Solana Discord!

**Comment by ignatievvictor** [comment]
There are some problem with a join to discord. There area thread on forum
with a 40 posts.
Can you help me with a joining please.
My discord: navysol9#5191

**Comment by jordansexton** [comment]
Solana Discord: https://discord.com/invite/solana

Once you join, use the #roles channel to select the Developer role. Then enter the #solana-pay channel.
