### ISSUE TITLE
[docs] Document configuration for the Point of Sale app

### ISSUE THREAD

**Issue by walter-grace** [solana-labs/solana-pay#55]
I am trying to figure out how to 
1. Switch to USDC 
2. Go to Mainnet-beta

Not sure where to switch to mainnet at in the code, cant seem to figure out if it is in the constants.ts file or elsewhere

**Comment by jordansexton** [comment]
Config goes here like this:

https://github.com/solana-labs/solana-pay/blob/fd8d034b97b3040e5e3c7ede653c8bc00c3857ff/point-of-sale/src/components/routes/RootRoute.tsx#L47-L69

Eventually we need to extract this config and make it support tokens from the token list or something.

**Comment by jordansexton** [comment]
Done in #82
