### ISSUE TITLE
[feature] Solana Pay on WooCommerce

### ISSUE THREAD

**Issue by igorradovanov** [solana-labs/solana-pay#62]
Hello Solana,
Thank you for making this amazing technology available to web developers around the world.

I am interested in building the WooCommerce plugin that will utilize Solana Pay. For that reason, is there a repo where I can contribute or the project is still on hold?

Thank you.

**Comment by Meergatto** [comment]
Hi @igorradovanov i'm working with this with 2 developers right now and we would love your assistance! It's not a public repo right now but you can email me justin@kickinknowledge.com and we can link up asap.

**Comment by geoffwhittington** [comment]
I built an offline payment gateway for KIN token - perhaps the code is useful as an example https://github.com/perkexchange/woocommerce-paymentgateway/

**Comment by Meergatto** [comment]
Thank you @geoffwhittington will review asap and I'm sure it will help!

**Comment by Meergatto** [comment]
Awesome, I'll post link to our discord here once I make it today/tomorrow and feel free to join, I'll also post repository here once public.

**Comment by Meergatto** [comment]
Discord link for Woocommerce (and eventually WordPress) integration too: https://discord.gg/uAKy9Ug7fb - I invited other devs should fill up over next couple days and we can all get started asap!

**Comment by jordansexton** [comment]
Closing this issue, but please feel free to add links to this. I would also accept a PR to look to WooLana on the docs!
