### ISSUE TITLE
Point of Sale - No progress circle or recent transactions on Mainnet Transactions

### ISSUE THREAD

**Issue by Dayton-IX** [solana-labs/solana-pay#68]
Hello! I'm trying out Solana Pay by using a forked version the point-of-sale demo, and I've found that the progress circle doesn't show up when doing Mainnet "real world" transactions. 

The transactions go through correctly, but the application does not show the transaction history, or the progress circle.

Everything works as intended on Devnet however.

I would appreciate any guidance or help, and I'm willing to try to fix the issue myself if I'm pointed in the right direction, thanks!

**Comment by jordansexton** [comment]
> the application does not show the transaction history, or the progress circle

Can you link a reproduction repo + branch?

**Comment by Dayton-IX** [comment]
> Can you link a reproduction repo + branch?

Yes: [here](https://github.com/Dayton-IX/solana-pay)

**Comment by jordansexton** [comment]
See https://github.com/solana-labs/solana-pay/issues/55#issuecomment-1029661592 -- you're not connected to mainnet. Your `ConnectionProvider` has to be changed too.

**Comment by Dayton-IX** [comment]
Ah, thanks!
