### ISSUE TITLE
[docs] Further Documentation on using NFT's in Transactions.

### ISSUE THREAD

**Issue by valentinmadrid** [solana-labs/solana-pay#70]
Solana's example when introducing Solana Pay was that it is possible to add an NFT to the transaction as a merchant and return it to the buyer. These could be digital copies of the product or even a receipt.
This feature is one of the most important that comes with Solana but isn't talked about in the Docs. 
It would be great to have a documentation for this.

Have a great day,
Valentin.

**Comment by valentinmadrid** [comment]
Update: Apparently his is not a part of Solana Pay yet, so this issue could be irrelevant.

**Comment by jordansexton** [comment]
Yeah, support for this feature within the protocol itself is being worked on. For now, it can be done off chain by observing the payment transaction then minting an NFT to the user in a separate transaction. https://github.com/solana-dev-adv/solana-cookbook/issues/239 is going to document this and then we'll link it from here.
