### ISSUE TITLE
[report] TypeError: Invalid URL: [object Object]↵    at URLImpl

### ISSUE THREAD

**Issue by billyjacoby** [solana-labs/solana-pay#71]
Trying  to import this library and use it in react-native but I get this error whenever i try to call `parseURL`.
 
I have all other polyfills installed for react-native, so this could be an issue with the implementation of `@solana/pay`.

I'll be looking into this issue on both sides in the coming week or two, but I wont be back in town for a few days so I wanted to document this here.

**Comment by billyjacoby** [comment]
Calling it on the value returned from the example QR code in the Readme gave me this error.

**Comment by jordansexton** [comment]
Not really enough context here and nothing I can readily test. Please provide detailed steps to reproduce, information about your build, a repo that reproduces the issue, or anything that would help debug the issue.

**Comment by jordansexton** [comment]
Closing as stale.
