### ISSUE TITLE
error with Layout.ts

### ISSUE THREAD

**Issue by UjjwalGupta49** [solana-labs/solana-pay#79]
I'm trying to integrate Solana Pay, making a pop up form that would generate an customized qr code for payments.
I get the following error (1) when import of sol-pay is enabled and the console points towards the line import (2)
Installation of package was done using npm

Is there a Solution?
### (1)
![image](https://user-images.githubusercontent.com/83765858/153710686-0fb694a1-f611-4d71-8713-336caacc9095.png)
### (2)
![image](https://user-images.githubusercontent.com/83765858/153710839-ea61a1b6-301a-473a-9a72-f3dfa840616e.png)

![image](https://user-images.githubusercontent.com/83765858/153710727-fe43f6d2-e3b9-4744-b795-d80929d4d4bd.png)

**Comment by jordansexton** [comment]
This sounds like a problem with Vite's default config or your project config. Another user reported an issue with Vite in https://github.com/solana-labs/solana-pay/issues/66

Unfortunately I can't help with issues that are specific to build toolchains we don't use within the project. We build the point of sale app with Parcel and it works without additional config.

**Comment by UjjwalGupta49** [comment]
`npm install -S @solana/buffer-layout`

resolved the error for me
for [reference](https://github.com/solana-labs/solana-program-library/issues/2683)

**Comment by MoneyBoy1x** [comment]
the above solution worked for me - I ran into the issue using a Mac M1 chip as well.
