### ISSUE TITLE
Testing the in-browser user experience

### ISSUE THREAD

**Issue by gxxcastillo** [solana-labs/solana-pay#84]
I'd like to integrate Solana Pay on my website via a button and I'd like to demo it to my team. How are people testing the start to end user flow?

I've gotten as far as a button that displays the QR code when clicked.  I'm on Android and the only way I've found of scanning the qr code is with the ftx app, using real funds.

**Comment by Anmolnoor** [comment]
If your issue is the real funds that you don't want to test with. Just go and create your own SPL token or you can say your crypto coins over Solana and use them.
However, I got this video maybe this help you to get your coins:: https://youtu.be/befUVytFC80
for creating your coin you need some Lamports (1 sol = 1B lamports) as gas fee or fee.
![image](https://user-images.githubusercontent.com/52135717/154295135-6fd5a994-f9cc-435b-a5f3-5c150da15001.png)

**Comment by Anmolnoor** [comment]
you can play with this example https://solana-labs.github.io/wallet-adapter/example/ to understand the flow in the browser.
If you want to understand the start to end-user flow solana web 3. Check out this web page I built (from [figment](https://learn.figment.io/)) for understanding Solana web 3 
still working on in-browser user experience

[Solana wallet](https://sleepy-galileo-ce19c5.netlify.app/)

![image](https://user-images.githubusercontent.com/52135717/154298444-8983c151-bf8d-4633-a678-e6e1cf27a300.png)
here you got 2 options to create a new account or recover the old one form Secret Recovery Phrase 
for test use this Secret Recovery Phrase 
```
girl stomach favorite snap man country paddle primary flag letter mushroom planet
```
after login, you can test the send and airdrop 
![image](https://user-images.githubusercontent.com/52135717/154299812-d06c383e-3bac-4158-b287-3549507c96f0.png)

**Comment by gxxcastillo** [comment]
Thanks @Anmolnoor. How would I get my own custom token or even the airdropped SOL into FTX?  Is there another option for testing the flow that doesn't require sending funds from my FTX account?

The specific issue I'm having is some kind of authenticator error with the FTX app, and it isn't allowing me to withdraw any funds and this just seems like a very unfortunate blocker to what I was hoping would be very low effort.

I just reread the docs at https://docs.solanapay.com/core/merchant-integration and noticed the callout to `simulateWalletInteraction(connection, url);`.  I guess the idea here is that I implement a `simulateWalletInteraction` method that would actually manually do the approval + submittal in order to avoid any real wallet interaction?

**Comment by gxxcastillo** [comment]
I was able to solve it by:

1. Following these steps: https://docs.solanapay.com/core/merchant-integration
2. Installing the crypto-please app on my android device
3. It doesn't seem the crypto-please app support devnet so I created a test wallet and sent it some funds. 
4. I scanned the qr code using the crypto-please app and successfully sent payment
