### ISSUE TITLE
[bug] wallet not show up to asked to approve the transaction

### ISSUE THREAD

**Issue by imanmoghimiq30** [solana-labs/solana-pay#86]
![image](https://user-images.githubusercontent.com/33248902/154296591-a8012359-ba7c-4e75-9e4f-bf19b4a3de91.png)
I turned "const connectWallet" to true and wallet detect and connect, but how I must approve transaction? nothing showed up!

**Comment by Anmolnoor** [comment]
https://solscan.io/tx/3sFx9SGYncWoXPSFWsKcTJj993icUaC45eaiz46nmqkiLDT4869ac8obea75rRJHJ4jheexGugbpesaYo8Jefdnn?cluster=devnet

**Comment by Anmolnoor** [comment]
https://docs.phantom.app/integrating/sending-a-transaction in browser transaction

**Comment by Anmolnoor** [comment]
this link is not working for me let's connect over discord 
My Id 
```
Noor2625#2650
```

**Comment by imanmoghimiq30** [comment]
> this link is not working for me let's connect over discord My Id
> 
> ```
> Noor2625#2650
> ```

I've done it!
It's weird, I used example code(URL describing a transfer for 1 SOL) and it worked, than started removing Memo, Message, Amount one by one to see what cause the problem, but after remove all of them it similar to my above link and still worked! as you see bellow 
![image](https://user-images.githubusercontent.com/33248902/154317106-d3829f34-8fcb-43ab-acd9-c24f632a85d2.png)

**Comment by gxxcastillo** [comment]
Hi, @imanmoghimiq30, what was the solution here?  How did you get your phantom browser extension to parse the QR code?

**Comment by gxxcastillo** [comment]
nm, I figured out something that worked for me. I listed the steps here: https://github.com/solana-labs/solana-pay/issues/84#issuecomment-1042547394

**Comment by imanmoghimiq30** [comment]
> Hi, @imanmoghimiq30, what was the solution here? How did you get your phantom browser extension to parse the QR code?

Can't say it's a solution, just used example code in doc for transfer 1 sol + my wallet address, and phantom brought approve screen.
***
<your wallet>&amount=1&label=Michael&message=Thanks%20for%20all%20the%20fish&memo=OrderId1234
***
than use my first format: 
<your wallet>&label=STARK

*Oh and make sure you set value to true in line 20 at: point-of-sale/src/components/routes/RootRoute.tsx

**Comment by imanmoghimiq30** [comment]
> nm, I figured out something that worked for me. I listed the steps here: [#84 (comment)](https://github.com/solana-labs/solana-pay/issues/84#issuecomment-1042547394)

I tested "crypto-please" too before even test phantom extension and I confirm it not support devnet. So I little bit confused did you try with real fund? or use testnet? because I'm sure I didn't see option to change network.

**Comment by gxxcastillo** [comment]
> Can't say it's a solution, just used example code in doc for transfer 1 sol + my wallet address, and phantom brought approve screen.
Sweet, thanks, I'll take a close look 👍 

> So I little bit confused did you try with real fund?
Yeah, I sent $.01 USDC
