### ISSUE TITLE
Adding Icons

### ISSUE THREAD

**Issue by walter-grace** [solana-labs/solana-pay#88]
Is there an easier way to add icons instead of using svg files? I have tried to add some custom icons and it doesn't seem to work properly (maybe I am formatting incorrectly).
Can the Solana icon inside the QR code be changed as well?
Thanks

**Comment by jordansexton** [comment]
All of the code is open source licensed, so it can be forked and modified. Changing the styles or replacing the Solana logo is your call, but I'd encourage you to consider how these changes might affect user recognition and their experience at the point of sale.

https://github.com/solana-labs/solana-pay/blob/master/core/src/createQR.ts is what contains the options to generate the QR. You could implement your own QR code styles by calling `createQROptions` and overriding what you want, or by providing your own options from scratch.

**Comment by walter-grace** [comment]
I just wanted to change the inside QR logo to USDC for example so the user knew they were paying with USDC not to hide the solana aspect that's all! Thank you
