### ISSUE TITLE
Incorrect SPEC - multiple public keys for "reference"

### ISSUE THREAD

**Issue by awesomeAB** [solana-labs/solana-pay#93]
According to the [official spec](https://docs.solanapay.com/spec#reference) we are allowed to use multiple public keys for reference, and indeed the [encodeURL](https://docs.solanapay.com/api/core/interface/EncodeURLComponents#reference) API from Solana Pay allows us to pass an array of public keys for this.

However, while trying to find the transaction signature - we use the [getSignaturesForAddress](https://docs.solana.com/developing/clients/jsonrpc-api#getsignaturesforaddress) API from Solana which expects this field to be a single public key.

Due to this, the [findTransactionSignature](https://docs.solanapay.com/api/core/function/findTransactionSignature) API from Solana pay only accepts a single public key. This means that we can't effectively use multiple public keys for the reference field 😦

Is this correct? If so, the documentation need to be corrected.

**Comment by jordansexton** [comment]
I responded on Discord, but this isn't a bug. The spec allows for multiple reference keys, and the reference implementation will encode them and parse them from a URL.

As you pointed out, `getSignaturesForAddress` will only allow one key, and `findTransactionSignature` uses this. If you want to make sure a transaction references multiple keys, you could use `getSignaturesForAddress` with one of them, and then further check that the other keys are also referenced as accounts.
