### ISSUE TITLE
findTransactionSignature() not finding the transaction by the provided reference

### ISSUE THREAD

**Issue by mortiet** [solana-labs/solana-pay#99]
Hey guys. I am testing solana pay to build a payment module based on it but I haven't been able to successfully finalize a payment based on the `payment-flow-merchant` example!
Steps that I follow:

1. Successful connection to `devnet`
```
Connection to cluster established: https://api.devnet.solana.com { 'feature-set': 3246413280, 'solana-core': '1.9.9' }
```
2. Simulate Checkout using my test merchant wallet and generate the payment URL:
```
solana:GrH51Zbp6czGypTUe2gcU6B6eB9BjTERx7K6XYoXE9au?amount=0.01&reference=4ZQAj72fPDzy99UNWZdupTd5rKMeoXn7r1nguzT5hxKA&label=MORTIE-PAY&message=MORTIE-PAY%20-%20your%20order%20-%20%23001234&memo=JC%234098
```
3. I then convert the URL to QR code and scan it with my second test wallet made on `Slope Wallet (Android)` while the network is set to `devnet`. Transaction succeeds and gets fully confirmed. I can see the `reference` and the `message` added to the URL shown while approving the transaction on my wallet.
https://solscan.io/tx/5TukQF9AEYjf7oDdPxpP7Bc6nNezzcANt8ooa5ztT8t36S4yfX8opmsLJYwwwxS8aQhwSYXSjFFBzgHL4dEiYgiy?cluster=devnet
4. Now at this stage, `findTransactionSignature()` never finds the transaction using the randomly generated `reference` key. I can't actually see this transaction using the `reference` on Solscan as well.

Can you help me with this, please?
Should I find that `reference` key somewhere in the transaction description in Solescan?
Thank you!

**Comment by jordansexton** [comment]
Ah, this is an issue with Slope. Their wallet is not including the `reference` field in the transaction. I've reported this to them!

**Comment by Merrick17** [comment]
same problme here , using phantom wallet

**Comment by scottwilson312** [comment]
Having the same issue with Phantom. Copy pasting the code from the "Merchant Integration", the txn goes thru just fine, but the `await fintTransactionSignature` just hangs indefinitely
